### ISSUE TITLE
Integration with competitive companion extension

### ISSUE THREAD

**Issue by Dilip23** [mfornet/acmx#1]
This tool helps me as i prefer VS Code for C++ than any other but it only supports Cofeforces and not anything.

While [Competitive Companion](https://github.com/jmerle/competitive-companion) can greatly parse many sites contests and problems. The list of sites is mentioned  in the above link as well.

If this tool can be integrated with Competitive Companion, It would be great for us all. @mfornet

**Comment by mfornet** [comment]
Great, all the parsing code is in typescript, so it should be easy to integrate with this tool. I will move the parsers here and update them to my interface. Thanks for the suggestion, I was too lazy to implement further parsers since I'm not actively competing anymore.

**Comment by mfornet** [comment]
Added support for Competitive Companion in version `0.2.0`.
Thanks for the suggestion.
