### ISSUE TITLE
[Windows] No Contest/Problem folder created if Username has white-spaces

### ISSUE THREAD

**Issue by VISHAL-RAJ-ROY** [mfornet/acmx#103]
![sad](https://user-images.githubusercontent.com/53266958/88634566-2cb62480-d0d4-11ea-90b5-ebd05a497b64.JPG)

**Comment by mfornet** [comment]
From our conversation it Competitive Companion is parsing test cases correctly, and it seems to be a bug with whitespaces in the path on windows.

**Comment by mfornet** [comment]
Fixed in #132
