### ISSUE TITLE
Extension not working on Windows

### ISSUE THREAD

**Issue by krsinghshubham** [mfornet/acmx#104]
the code-companion is not working for me. fixed the ports and everythinhg but not parsing codeforces contests at all.

**Comment by mfornet** [comment]
@krsinghshubham from what I can see in this issue https://github.com/jmerle/competitive-companion/issues/111 your problem is related with the extension in your browser, it doesn't look to be parsing the problems (so it is never submitted to the acmx extension).

**Comment by krsinghshubham** [comment]
hi, do i manually need to open any folder in vsc after running the chrome extension ? or the extension opens it own ?

**Comment by krsinghshubham** [comment]
![acmx 1Annotation 2020-08-10 181632](https://user-images.githubusercontent.com/47324260/89784170-d61a0300-db35-11ea-97df-633832cf7ce2.png)
![acmx 2 Annotation 2020-08-10 181704](https://user-images.githubusercontent.com/47324260/89784172-d6b29980-db35-11ea-9426-c7c59ff8a10f.png)


with refrence to above comment, are these settings which are default is fine. ( port in extension is set correctly).

**Comment by mfornet** [comment]
> hi, do i manually need to open any folder in vsc after running the chrome extension ? or the extension opens it own ?

It should open vsc automatically after click on the chrome extension (if it didn't fail somehow, it shouldn't fail for example with codeforces). Settings looks good to me, however If you are on windows consider replacing **Home Path** and **Library** to a full path that currently exists instead of using **$HOME**.

**Comment by krsinghshubham** [comment]
![10 acmx new Annotation 2020-08-10 201058](https://user-images.githubusercontent.com/47324260/89795309-dae6b300-db45-11ea-9226-99cdacb824d9.png)


tried , but sadly no result :(

**Comment by Salil03** [comment]
#d493f4cb30bb249a7beb947e179307dc1e345fed should fix it

**Comment by krsinghshubham** [comment]
yes , fixed !.
Thanks a lot.
