### ISSUE TITLE
Run all test cases even though some fail.

### ISSUE THREAD

**Issue by Dogacel** [mfornet/acmx#106]
In some contests, many easy problems have multiple solutions. I am not a fan of writing a custom checker for such easy problems because I am losing points from time. I think there should be a "forced run" option to run all test cases even though some fail and show you the output. Otherwise I am manually running the test cases from the command line which is a bit time consuming and extension could have been better anyways.

**Comment by mfornet** [comment]
@Dogacel I agree with you. I plan to move to an UI similar to competitive-programming-helper which will be better in this sense, but definitely it will take more time, and hopefully contributions from community. 

Currently I also have this issue, writing checker definitely is a bad idea mid contest. My approach is: 

Run the program, on the first WA, eye-ball and check output is correct, copy-past content from .out to .ans, and run again :)
Hope this helps as a hack today.

**Comment by mfornet** [comment]
I'm tracking this in #40
