### ISSUE TITLE
Error parsing special characters in the problem name

### ISSUE THREAD

**Issue by aniervs** [mfornet/acmx#108]
I was doing [this](https://omegaup.com/arena/CIIC2018-Practice/practice/#problems/CIIC2018-Arbol) problem and some others from the same competition, and happened this: if compilation fails, it doesn't show the syntaxis errors, and in the integrated terminal it shows the path of the code with weird characters.

This is the actual path of the code:
"$HOME/.acmx/solutions/omegaUp - CIIC 2018 - Práctica/C. Árbol NP-K/template.cpp"

**Comment by Salil03** [comment]
https://www.npmjs.com/package/sanitize-filename might help. Also in #103
