### ISSUE TITLE
Selecting checker doesn't work

### ISSUE THREAD

**Issue by Salil03** [mfornet/acmx#110]
Even though I have selected rcmp6.cpp checker, my AC code gives wrong answer with checker. Also rcmp6 is not present in the checker folder.

**Comment by Dogacel** [comment]
I think settings the "checker.value" should default to checker.cpp in the attic folder. Because selecting a checker only creaters checker.cpp but it doesn't change the config so I still get WA.

**Comment by mfornet** [comment]
Fixed in #113 (Will close after publishing new version)
