### ISSUE TITLE
Ambigous Code Layout

### ISSUE THREAD

**Issue by raj-sahu** [mfornet/acmx#123]
whenever i run a code the code gets itself open along with the output how to resolve this, can somebody help
![image](https://user-images.githubusercontent.com/57115538/106360535-df469880-633e-11eb-86df-b48ec0c0149c.png)

**Comment by mfornet** [comment]
Thanks for submitting this issue. This is happening to me too after a recen upgrade in vscode. It will be fixed with the new layout when we merge #124

**Comment by mfornet** [comment]
This issue was introduced unexpectedly at some vscode update, and it seems to be fixed at this point (without any change on acmx itself). I'm currently running VSCode Version: 1.66.2 (Universal) Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977.

Closing this; since it is no longer relevant.
