### ISSUE TITLE
Run programs on integrated terminal.

### ISSUE THREAD

**Issue by mfornet** [mfornet/acmx#13]
Right now compile errors and standard error output is displayed in the terminal calling `echo`. 
While this is a useful feature to have the way it is implemented is far from ideal since:
- it is not cross-platform.
- echoed commands become part of the terminal history.

The new proposal is capturing such errors, and show them in separate editor file instead of using terminal for that.

**Comment by Salil03** [comment]
Or you could just run the compilation and each test case in the integrated terminal. This also gives better control to the user.

**Comment by Salil03** [comment]
And on windows, if there is a compilation error, vscode crashes after that. I suspect that will not happen if compilation is done in integrated terminal. Also I can't see the error properly in the current mechanism. It is all jumbled due to the echo commands.

**Comment by mfornet** [comment]
I like a lot the idea of using integrated terminal instead. You can take a look at this example here: https://github.com/microsoft/vscode-extension-samples/tree/master/terminal-sample

@Salil03 AFAIR the issue with running the commands in integrated terminal was setting a time-limit / capturing the output. So if this is solved everything else should be straightforward.

**Comment by mfornet** [comment]
Ideally solving this issue might cover solving #25. The idea is to create a function that receive a command and a time limit and return an object with data from the execution, for example, exit code, stdout, stderr, time spent, memory spent. Today this function is partially `timedRun`, but I made `timedRun` only to run a single test case. With this new function we should replace all `spawnSync` with it.

**Comment by Salil03** [comment]
#47
