### ISSUE TITLE
Not able to use C++11 or higher 

### ISSUE THREAD

**Issue by prince-baweja-tivo** [mfornet/acmx#130]
Errors while compiling: B_Pleasant_Pairs.cpp:7:5: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]     auto x = 5;  
If possible, then how can i run my program in c++11 or higher.

**Comment by prince-baweja-tivo** [comment]
Solution is here to use c++ 11 or higher in this extension.

Found the solution  -  
Steps to resolve this issue 
1. Go to settings in VS code. 
2. Go to Extensions. 
3, Choose Competitive programming helper extension. 
4. Search this — Cph › Language › Cpp: Args , or got 5. Paste this (-std=c++17) in the box

And boom, This solution worked for me.

Screenshot for reference — https://drive.google.com/file/d/1P3_2vlEylzVik30e-2-8sGyy3YAI0nji/view?usp=sharing

**Comment by mfornet** [comment]
From the configuration you are using it looks like you are confusing this extension with https://github.com/agrawal-d/cph

**Comment by prince-baweja-tivo** [comment]
Yeah correct, that's my bad. Thanks for pointing out.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
