### ISSUE TITLE
Does not show Testcases UI when terminal position moved

### ISSUE THREAD

**Issue by mahbd** [mfornet/acmx#131]
I cloned and build the latest [commit](https://github.com/mfornet/acmx/commit/6f41be2a4a17bf203c73984fe9489895d2c7e96a) which was made two days ago. The test case UI is really beautiful. But there is only one small problem, The testcases UI doesn't show if I move terminal position such as bottom to left.  Restarting VS code solves the problem. This problem is not so serious because no one will change terminal so many times but good to know.

**Comment by mfornet** [comment]
Thanks for the feedback. 

cc @dgc9715

**Comment by mfornet** [comment]
Hi @mahbd I was trying this; and as far as I understand the problem is that you can't have open at the same time both the terminal and the webview! is that correct? I think this is the intended behavior. I don't think we will be changing this.
