### ISSUE TITLE
How to prevent acmx from opening a new VSCode instance?

### ISSUE THREAD

**Issue by ftiasch** [mfornet/acmx#139]
Generally, I am running a workspace to solve tasks. 

When I click the button to parse a new task, the workspace is closed automatically and a new folder is opened instead. Then I need to reopen my configured workspace to get my developing environment set.

I wonder, if there is an option to prevent such behavior? Thanks in advance.

**Comment by mfornet** [comment]
This is the intended behaviour. What happens under the hood is that the task is downloaded to a "special" location and this folder is opened automatically.

Can you describe more about how do you reopen your configured workspace? so I can try to re-open it while opening the new task.

**Comment by ftiasch** [comment]
Maybe my previous wording is unclear. 

Simply, I have a well-configured Code instance running, and I don't like it to be replaced. In other word, is it possible the whole process of "download + open the folder" into two separated parts and make the later one (the "open the folder" part) to be optionally disabled?

**Comment by mfornet** [comment]
Not trivially; the problem is downloaded to this special location! 

I guess the option you need is that the problem is downloaded to the current open directory. 

That is doable, if you are open to contribute to this repository I can guide you about how to add this feature.

**Comment by ftiasch** [comment]
I have opened a new PR #140 containing the required changes.

Sadly I didn't manage to understand how to compile & run the extension. If you have time, could you have an eye on the PR?

**Comment by ftiasch** [comment]
@mfornet Finally I figured out to use `vsce package` to package the extension locally and successfully achieved my desired effect. 

If it looks good to you, hope the pull request can be merged and released soon.

Above all, thanks for the great extension.
