### ISSUE TITLE
Show error if compiling is unsuccessful

### ISSUE THREAD

**Issue by Salil03** [mfornet/acmx#2]
This extension does not show error message or warning message that g++ outputs if compilation is unsuccessful. Also `cerr` output is not shown.

**Comment by Salil03** [comment]
Or better still can you run the compilation in the integrated terminal? Anyway a terrific job you did!!

**Comment by mfornet** [comment]
Yes I'll try, it was already suggested but haven't had the time to implement it. I will take a look at it this weekend. This is something I needed too from previous competitions.

Thanks :flushed: :smile: !

**Comment by Salil03** [comment]
How is the progress?

**Comment by Salil03** [comment]
You can check this out https://stackoverflow.com/questions/39183985/using-integrated-terminal-in-a-vs-code-extension

**Comment by Salil03** [comment]
Please resolve this issue. When this issue is resolved acmx will be the perfect extension for cp. It is very difficult to debug code without looking at the error message.

**Comment by Salil03** [comment]
Please reply

**Comment by mfornet** [comment]
@Salil03 sorry for the delay. I manage to update the extension on a flight yesterday. Right now I'm not with my PC. I'll submit changes asap and let you know. 

Consider joining to the Telegram group for active discussion. https://t.me/joinchat/FksZ0BSkGh7anvpFYisjMw

**Comment by Salil03** [comment]
No problem. I have joined the telegram group. Once again a great job on the extension!!!

**Comment by mfornet** [comment]
722b00b3b824bc260c59dbe01a4a7ffc9e814d1f
