### ISSUE TITLE
Give ability to run the file in terminal.

### ISSUE THREAD

**Issue by Salil03** [mfornet/acmx#4]
This would enable the user to use this extension for interactive problems and also to give custom input in normal problems.

**Comment by mfornet** [comment]
@Salil03 what is the behavior you are expecting from running the file in terminal? This can be done right now.

1. Compile the file: `ACMX: Compile`
2. Open the terminal in vscode, which by default is opened in your workspace.
3. Type `./attic/sol.exe` to run your solution.

This way you can provide custom input or handle interactive problems. I'm closing this now, but if you have something different in mind with this issue let me know and we open it again.
