### ISSUE TITLE
Persistent generated tests

### ISSUE THREAD

**Issue by mfornet** [mfornet/acmx#41]
All input tests created using generated should be stored after each run.

Generator should create a new test deterministically given a seed from the standard input.

The files created will be of the form:

```
testcases/
  test-$seed.gen.in
  test-$seed.gen.out
```

Test cases should be erased before creating a new batch of tests.

**Comment by Salil03** [comment]
Isn't this same as #39?

**Comment by mfornet** [comment]
Same as #41
