### ISSUE TITLE
Don't like new "diff" method for comparing test cases

### ISSUE THREAD

**Issue by testitem** [mfornet/acmx#52]
In VScode, the diff editor normally displays diffs like this:

<img width="691" alt="image" src="https://user-images.githubusercontent.com/19212916/80952046-9acbb200-8e2b-11ea-90a0-1a9e3c196f9d.png">

In competitive programming, this is extremely unhelpful, because it is normally the case that there are **differences** on certain lines, as opposed to there being inserted / deleted lines in the input and output.

I would rather just have the expected output / normal output side by side.

**Comment by mfornet** [comment]
Thanks for the feedback @testitem. Totally agree with you. Will rollback the diff, but keep displaying test cases side by side.

**Comment by Salil03** [comment]
Fixed with #53
