### ISSUE TITLE
An unknown error occurred (on compilation error)

### ISSUE THREAD

**Issue by mfornet** [mfornet/acmx#57]
<img width="1679" alt="Screen Shot 2020-05-08 at 12 18 02 AM" src="https://user-images.githubusercontent.com/28708963/81370095-42faa880-90c2-11ea-9a0d-7e0d096e99ff.png">

There are not available logs.

**Comment by Salil03** [comment]
Maybe add something in the quotes when we throw an error: https://github.com/mfornet/acmx/blob/4108389df739c4664ce8b4ab399df398e51b112d/src/core.ts#L545

**Comment by mfornet** [comment]
Should be fixed in #59
