### ISSUE TITLE
Missing 2nd Problem while parsing Contests

### ISSUE THREAD

**Issue by rashedmyt** [mfornet/acmx#6]
I have tried with codechef and codeforces.. it doesn't create any folders for 2nd problem in particular. I tried checking if it was issue with companion extension but not - In debug, all problems were sent by the extension.

**Comment by rashedmyt** [comment]
VS Code - 1.37.1
OS - Windows 10 Home Single Language
acmX - 0.2.3

Tested links:
Codeforces - https://codeforces.com/contest/1205
Codechef - https://codechef.com/AUG19B

settings.json:
```
{
    "acmx.companion.port": 9550,
    "acmx.configuration.solutionPath": "D:\\CP\\",
}
```

let me know if you need any extra details

**Comment by mfornet** [comment]
It works good for me on these scenarios, and other multiple contests. I have a clue about what could generate this issue, and is about the server listening for competitive companion extension push. I think it is fixed now.

I'm closing this, if someone see this issue again, feel free to open it.
