### ISSUE TITLE
What was this update???

### ISSUE THREAD

**Issue by testitem** [mfornet/acmx#83]
Now it won't parse any problems.... it's not working anymore.... I don't want it to be updated without consent.... please help!!!!

**Comment by testitem** [comment]
The entire settings file changed, and it's not working anymore

**Comment by Salil03** [comment]
You can revert back to previous version like this:
https://i.stack.imgur.com/Yh0jv.gif

**Comment by Salil03** [comment]
You can revert back to previous version like this:
https://i.stack.imgur.com/Yh0jv.gif

Just click on `Install another version` in the extension marketplace

**Comment by testitem** [comment]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/19212916/82139644-fea69f80-985b-11ea-8ddf-d95dd7ad873f.png">

**Comment by Salil03** [comment]
Just wait for one minute after opening vscode and see if it is working

**Comment by testitem** [comment]
> You can revert back to previous version like this:
> https://i.stack.imgur.com/Yh0jv.gif
> 
> Just click on `Install another version` in the extension marketplace

THANK YOU SO MUCH, YOU HAVE SAVED MY LIFE

**Comment by testitem** [comment]
<3 <3

**Comment by Salil03** [comment]
See this page for information on configuration: https://github.com/mfornet/acmx/wiki/Settings-and-Commands

**Comment by mfornet** [comment]
@testitem sorry for the inconvenience. I pushed a new version with all changes rolled back (0.3.1)

**Comment by mfornet** [comment]
For those interested, here is the solution https://github.com/mfornet/acmx/pull/86/files#diff-11e9f7f953edc64ba14b0cc350ae7b9dR39. Culprit was webpack + static folder combination.
