### ISSUE TITLE
Submit to Codeforces

### ISSUE THREAD

**Issue by mfornet** [mfornet/acmx#88]
This issue cover a subset of #35. Submit solution to Codeforces with a button using [cf-tool](https://github.com/xalanq/cf-tool)

This can be easily implemented for now before implementing the submission for all platforms.

Proposal:
1. Users should install cf-tools manually and have a global command that allows using it.
2. When there is a problem open and is detected to be from codeforces enable the button to submit.
3. When the button is clicked it should call the command that submits the solution.

It will require to store in the config.json details of the problem from competitive companion.

**Comment by Salil03** [comment]
It would be better to not create a button and instead show this command in command pallete because there will be too many buttons.

Alternatively, remove the stress and upgrade buttons and add the submit button.
