### ISSUE TITLE
I install plugin but when write code and click acmx:Run code appear error WA in test 0?

### ISSUE THREAD

**Issue by tarek7889nady** [mfornet/acmx#9]
please tell if you can fix this error ....

**Comment by mfornet** [comment]
I guess you are sure that your code is Accepted. If the problem requires a checker that might be the problem. Can you provide me link to the problem, or solution + testcases.

**Comment by tarek7889nady** [comment]
https://ideone.com/vMiS35    ::solution
https://codeforces.com/contest/231/problem/A   ::this problem

**Comment by Salil03** [comment]
Even I am getting this on windows but on ubuntu it works fine

**Comment by mfornet** [comment]
The problem was that windows only run programs if their extension is `.exe` :man_facepalming: 
It should be solved in version [0.2.5](7d6054f7ca502fc024626c582a7e19e1fe01b4a3). 

I'm closing this here, if this doesn't fix the problem for you let me know. cc: @Salil03 @tarek7889nady

**Comment by Salil03** [comment]
This issue still persists

**Comment by mfornet** [comment]
We discuss and solved this offline, the issue was about the global attic folder which was invalid. New users should not experience this issue anymore.

The fix was removing the global `attic` folder and restarting the vscode (to recreate the folder from scratch).
