### ISSUE TITLE
Why is compile command not present in configuration

### ISSUE THREAD

**Issue by Salil03** [mfornet/acmx#91]
Earlier versions of acmx had option to set compile command. I can't see it in the latest version. Any reason why?

**Comment by mfornet** [comment]
Not sure what version you are using, but if you are using v0.3.2 from releases then the compile line is called prerun and it is located in the language configuration on `~/.acmx/languages/cpp.json`

Check here: https://github.com/mfornet/acmx/wiki#custom-compile-and-run-command
